version: '2'

services:
  mysql:
    image: mysql
    container_name: mysql
    ports:
     - "33006:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sineo
  php:
    image: mehrdadkhah/php7
    container_name: php7
    links:
     - mysql:mysql
    ports:
     - "9000:9000"
    volumes:
     - ./:/var/www/html/
  nginx:
    image: nginx
    container_name: nginx_php7
    links:
     - php:fpm
     - mysql:mysql
    ports:
     - "8080:80"
    volumes:
     - ./:/var/www/html/
     - ./sineo.conf:/etc/nginx/conf.d/default.conf
