<?php

namespace AppBundle\Repository;

/**
 * fuelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class fuelRepository extends \Doctrine\ORM\EntityRepository
{
}
