<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Vehicle;

/**
 * InterventionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InterventionRepository extends \Doctrine\ORM\EntityRepository
{
    public function findForVehicle(Vehicle $vehicle)
    {
        return $this->createQueryBuilder('i')
            ->leftJoin('i.vehicleInterventions', 'vi')
            ->where('i.required = :required')
            ->orWhere('vi.vehicle = :vehicle')
            ->setParameter('required', true)
            ->setParameter('vehicle', $vehicle)
            ->orderBy('i.id')
            ->getQuery()
            ->execute()
        ;
    }
}
