<?php

namespace AppBundle\Repository;

/**
 * InterventionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InterventionRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByTypeInterventionTransition($transition)
    {
        return $this->createQueryBuilder('i')
            ->join('i.typeIntervention', 't')
            ->where('t.transition = :transition')
            ->setParameter('transition', $transition)
            ->getQuery()
            ->execute()
        ;
    }
}
