<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Vehicle;

/**
 * TransportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransportRepository extends \Doctrine\ORM\EntityRepository
{
}
