<?php

namespace AppBundle\Repository;

/**
 * TypeInterventionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeInterventionRepository extends \Doctrine\ORM\EntityRepository
{
}
