<?php

namespace AppBundle\Repository;

/**
 * VehicleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehicleRepository extends \Doctrine\ORM\EntityRepository
{
    public function findVehicleToExpertise()
    {
        return $this->createQueryBuilder('v')
            ->leftJoin('v.interventions', 'i')
            ->where('i.id is null')
            ->getQuery()
            ->execute()
        ;
    }

    public function findVehicleToControl()
    {
        return $this->createQueryBuilder('v')
            ->leftJoin('v.interventions', 'i')
            ->where('i.id is not null')
            ->getQuery()
            ->execute()
        ;
    }
}
