<?php

namespace AppBundle\Repository;

/**
 * VehicleInterventionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehicleInterventionRepository extends \Doctrine\ORM\EntityRepository
{
}
