<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Vehicle;

/**
 * VehicleInterventionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehicleInterventionRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByTypeInterventionTransitionAndVehicle($transition, Vehicle $vehicle)
    {
        return $this->createQueryBuilder('vi')
            ->join('vi.intervention', 'i')
            ->join('i.typeIntervention', 't')
            ->where('t.transition = :transition')
            ->andWhere('vi.vehicle = :vehicle')
            ->setParameter('transition', $transition)
            ->setParameter('vehicle', $vehicle)
            ->getQuery()
            ->execute()
        ;
    }
}
