security:
    encoders:
        AppBundle\Entity\User: bcrypt

    role_hierarchy:
        ROLE_USER:          ROLE_USER

        ROLE_EXPERT:
            - ROLE_EXPERT
            - ROLE_USER
        ROLE_CONTROL:
            - ROLE_CONTROL
            - ROLE_USER
        ROLE_TRANSPORTER:
            - ROLE_TRANSPORTER
            - ROLE_USER
        ROLE_PHOTOGRAPHER:
            - ROLE_PHOTOGRAPHER
            - ROLE_USER
        ROLE_MECHANICIAN:
            - ROLE_MECHANICIAN
            - ROLE_USER
        ROLE_BODYBUILDER:
            - ROLE_BODYBUILDER
            - ROLE_USER
        ROLE_BEAUTICIAN:
            - ROLE_BEAUTICIAN
            - ROLE_USER
        ROLE_CLEANER:
            - ROLE_CLEANER
            - ROLE_USER

        ROLE_MASTER_WORKSHOP:
            - ROLE_MECHANICIAN
            - ROLE_BEAUTICIAN
            - ROLE_BODYBUILDER
            - ROLE_CLEANER
            - ROLE_PHOTOGRAPHER

        ROLE_ADMIN:
            - ROLE_USER
            - ROLE_CONTROL
            - ROLE_TRANSPORTER
            - ROLE_EXPERT
            - ROLE_MASTER_WORKSHOP

    providers:
        user:
            entity:
                class: AppBundle:User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                username_parameter: login[_username]
                password_parameter: login[_password]
            logout:
                invalidate_session: true
                path: /logout
            remember_me:
                secret: '%secret%'
                lifetime: 604800
                path: /
                remember_me_parameter: login[_remember_me]

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/expertise/, role: ROLE_EXPERT }
        - { path: ^/control/, role: ROLE_CONTROL }
        - { path: ^/mechanical/, role: ROLE_MECHANICIAN }
        - { path: ^/bodywork/, role: ROLE_BODYBUILDER }
        - { path: ^/cosmetic/, role: ROLE_PAINTER }
        - { path: ^/cleaning/, role: ROLE_CLEANER }
        - { path: ^/photo/, role: ROLE_PHOTOGRAPHER }

