services:
    form.register:
        class: AppBundle\Form\RegisterType
        arguments: [ '@security.authorization_checker' ]
        tags:
            - { name: form.type }

    form.intervention:
        class: AppBundle\Form\InterventionType
        arguments: [ '@doctrine' ]
        tags:
            - { name: form.type }

    form.admin.update_user:
        class: AppBundle\Form\UpdateUserType
        arguments: [ '@security.password_encoder' ]
        tags:
            - { name: form.type }

    app.listener.intervention_transition:
        class: AppBundle\Listener\InterventionTransitionListener
        arguments: ['@state_machine.vehicle', '@session']
        tags:
            - { name: kernel.event_subscriber }
